name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m -Dfile.encoding=UTF-8"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            build-tools;34.0.0
            ndk;25.2.9519653
            platform-tools
            platforms;android-34
          accept-android-sdk-licenses: true

      - name: Create Minimal Gradle Setup
        run: |
          # Create minimal settings.gradle
          echo "rootProject.name = 'VoiceAvtar'" > settings.gradle
          echo "include ':app'" >> settings.gradle
          
          # Create gradle wrapper properties
          mkdir -p gradle/wrapper
          cat > gradle/wrapper/gradle-wrapper.properties <<EOF
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          
          # Download gradle wrapper
          curl -sL -o gradlew https://raw.githubusercontent.com/gradle/gradle/master/gradlew
          chmod +x gradlew
          
          # Download wrapper jar
          curl -sL -o gradle/wrapper/gradle-wrapper.jar \
            https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar

      - name: Build Debug APK
        run: |
          ./gradlew :app:assembleDebug \
            --no-daemon \
            --stacktrace \
            --info \
            --max-workers=2 \
            -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxMetaspaceSize=512m"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
